# -*- coding: utf-8 -*-
"""AI_project_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1102kmWUDe8dfzw-kcTfRhPmvdZ0_N-Ki
"""

responses = {
    "hello": "Hello! Nice to meet you. How can I help you today?",

    "hi": "Hi there! Hope you're having a great day.",

    "how are you": "I'm doing great! Thanks for asking. How about you?",

    "name": "My name is DecodeBot. I'm a simple AI chatbot created using Python.",

    "who created you": "I was created by an AI Intern as part of the DecodeLabs training program.",

    "help": "I can respond to greetings, answer simple questions, and have a basic conversation with you.",

    "thanks": "You're most welcome! Feel free to ask anything else.",

    "good morning": "Good morning! Wishing you a productive and successful day ahead.",

    "good afternoon": "Good afternoon! How can I assist you today?",

    "good evening": "Good evening! Hope your day is going well.",

    "bye": "Goodbye! Have a wonderful day and take care."
}

while True:
    # lower means convert text into smaller
    # strip used for the remove extra spaces
    user_input = input("You: ").lower().strip()
#if condition
    if user_input == "bye":
        print("Bot: Goodbye!")
        break

    reply = responses.get(
        user_input,
        "I don't understand."
    )

    print("Bot:", reply)