# -*- coding: utf-8 -*-
"""AI_Project_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiZrgd-Z9FtUlXR3GnvoiBtiYpbeVkeo
"""

# ==========================================
# AI Recommendation System
# Project 3 - DecodeLabs
# ==========================================

print("==========================================")
print("     AI Recommendation System")
print("==========================================")
print("Welcome! 😊")
print("This system recommends courses based on your interests.")
print()

# Step 2: Taking user interests

interest1 = input("Enter your first interest: ")
interest2 = input("Enter your second interest: ")
interest3 = input("Enter your third interest: ")

user_interests = [interest1, interest2, interest3]

print()
print("Your interests are:")
print(user_interests)

# Step 3: Creating a dataset

courses = {
    "Python for Beginners": ["python", "programming", "coding"],
    "Machine Learning": ["python", "ai", "machine learning"],
    "Artificial Intelligence": ["ai", "machine learning", "deep learning"],
    "Web Development": ["html", "css", "javascript"],
    "Data Science": ["python", "data", "machine learning"],
    "Graphic Design": ["photoshop", "illustrator", "design"],
    "Flutter App Development": ["flutter", "dart", "mobile"],
    "Cyber Security": ["network", "security", "hacking"]
}

print("Available Courses:\n")

for course in courses:
    print(course)

# Step 4: Matching user interests with course tags

print("\nRecommended Courses:\n")

for course, tags in courses.items():

    match_count = 0

    for interest in user_interests:

        if interest.lower() in tags:
            match_count += 1

    if match_count > 0:
        print(course, "->", match_count, "interest(s) matched")

# Step 5: Sorting recommendations by highest score

recommendations = []

for course, tags in courses.items():
    match_count = 0

    for interest in user_interests:
        if interest.lower() in tags:
            match_count += 1

    if match_count > 0:
        recommendations.append((course, match_count))

recommendations.sort(key=lambda x: x[1], reverse=True)

print("Top Recommended Courses:\n")

for course, score in recommendations:
    print(course, "-> Score:", score)

print("========== TOP 3 RECOMMENDATIONS ==========\n")

top_3 = recommendations[:3]

for i, (course, score) in enumerate(top_3, start=1):
    print(f"{i}. {course} (Score: {score})")

# Step 7: Display Best Recommendation

print("\n================================")

if len(recommendations) > 0:
    best_course = recommendations[0]

    print("🏆 Best Recommendation")
    print("Course :", best_course[0])
    print("Score  :", best_course[1])

else:
    print("No recommendation found.")

print("================================")

# Step 8: Display Match Percentage

print("\n========== MATCH PERCENTAGE ==========\n")

for course, score in recommendations:
    percentage = (score / len(user_interests)) * 100
    print(f"{course} --> {percentage:.0f}% Match")

# Version 2: AI Recommendation System using TF-IDF and Cosine Similarity

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully!")

# Step 2: Creating AI dataset

course_names = [
    "Python for Beginners",
    "Machine Learning",
    "Artificial Intelligence",
    "Web Development",
    "Data Science",
    "Graphic Design",
    "Flutter App Development",
    "Cyber Security"
]

course_features = [
    "python programming coding beginner",
    "python ai machine learning algorithms",
    "artificial intelligence ai machine learning deep learning",
    "html css javascript frontend website",
    "python data analysis machine learning statistics",
    "photoshop illustrator design creativity",
    "flutter dart mobile app development",
    "network security hacking cyber protection"
]

print("AI Dataset Created Successfully!")

# Step 3: Taking user preferences for AI recommendation

user_input = input("Enter your interests separated by commas: ")

print("User Profile:")
print(user_input)

# Step 4: Convert text into vectors using TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

# Ensure course_features is defined, in case previous cells were not run or kernel restarted.
course_names = [
    "Python for Beginners",
    "Machine Learning",
    "Artificial Intelligence",
    "Web Development",
    "Data Science",
    "Graphic Design",
    "Flutter App Development",
    "Cyber Security"
]

course_features = [
    "python programming coding beginner",
    "python ai machine learning algorithms",
    "artificial intelligence ai machine learning deep learning",
    "html css javascript frontend website",
    "python data analysis machine learning statistics",
    "photoshop illustrator design creativity",
    "flutter dart mobile app development",
    "network security hacking cyber protection"
]


all_text = course_features + [user_input]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(all_text)

print("Text converted into vectors successfully!")
print("Matrix Shape:", tfidf_matrix.shape)

# Step 5: Calculate Cosine Similarity

from sklearn.metrics.pairwise import cosine_similarity

similarity_scores = cosine_similarity(
    tfidf_matrix[-1:],      # User Input
    tfidf_matrix[:-1]       # All Courses
)

print("Similarity Scores:\n")
print(similarity_scores)

# Step 6: Attach course names with similarity scores

scores = similarity_scores[0]

ai_recommendations = []

for i in range(len(course_names)):
    ai_recommendations.append((course_names[i], scores[i]))

ai_recommendations.sort(key=lambda x: x[1], reverse=True)

print("===== AI Recommended Courses =====\n")

for course, score in ai_recommendations[:3]:
    print(f"{course} --> {score:.2f} similarity")

print("\n🏆 Best AI Recommendation\n")

best_course = ai_recommendations[0]

print("Course:", best_course[0])
print("Similarity Score:", round(best_course[1], 2))

print("\nThank you for using the AI Recommendation System!")

# ==========================================
# AI Recommendation System
# Project 3 - DecodeLabs
# Developed by: Your Name
# ==========================================

# Import Libraries
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("="*60)
print("        AI RECOMMENDATION SYSTEM")
print("="*60)

# ===============================
# Dataset
# ===============================

course_names = [
    "Python for Beginners",
    "Machine Learning",
    "Artificial Intelligence",
    "Web Development",
    "Data Science",
    "Graphic Design",
    "Flutter App Development",
    "Cyber Security"
]

course_features = [
    "python programming coding beginner",
    "python ai machine learning algorithms",
    "artificial intelligence ai machine learning deep learning",
    "html css javascript frontend website",
    "python data analysis machine learning statistics",
    "photoshop illustrator design creativity",
    "flutter dart mobile app development",
    "network security hacking cyber protection"
]

print("\nAvailable Courses:\n")

for course in course_names:
    print("-", course)

# ===============================
# User Input
# ===============================

print("\nEnter your interests.")
print("Example: python, ai, machine learning\n")

user_input = input("Your Interests: ")

# ===============================
# TF-IDF Vectorization
# ===============================

all_text = course_features + [user_input]

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(all_text)

# ===============================
# Cosine Similarity
# ===============================

similarity_scores = cosine_similarity(
    tfidf_matrix[-1:],
    tfidf_matrix[:-1]
)

scores = similarity_scores[0]

# ===============================
# Store Recommendations
# ===============================

recommendations = []

for i in range(len(course_names)):
    recommendations.append((course_names[i], scores[i]))

# ===============================
# Sort Recommendations
# ===============================

recommendations.sort(
    key=lambda x: x[1],
    reverse=True
)

# ===============================
# Display Results
# ===============================

print("\n")
print("="*60)
print("        TOP AI RECOMMENDATIONS")
print("="*60)

for i, (course, score) in enumerate(recommendations[:3], start=1):

    percentage = score * 100

    print(f"{i}. {course}")
    print(f"   Similarity Score : {score:.2f}")
    print(f"   Match Percentage : {percentage:.1f}%")
    print()

# ===============================
# Best Recommendation
# ===============================

best_course = recommendations[0]

print("="*60)
print("🏆 BEST RECOMMENDATION")
print("="*60)

print("Course :", best_course[0])
print("Similarity Score :", round(best_course[1],2))
print("Match Percentage :", round(best_course[1]*100,1),"%")

# ===============================
# Thank You
# ===============================

print("\n"+"="*60)
print("Thank You for using AI Recommendation System!")
print("Powered by DecodeLabs Project 3")
print("="*60)run

while True:

    # User Input
    user_input = input("Enter your interests: ")

    # TF-IDF
    all_text = course_features + [user_input]

    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(all_text)

    # Cosine Similarity
    similarity_scores = cosine_similarity(
        tfidf_matrix[-1:],
        tfidf_matrix[:-1]
    )

    scores = similarity_scores[0]

    recommendations = []

    for i in range(len(course_names)):
        recommendations.append((course_names[i], scores[i]))

    recommendations.sort(key=lambda x: x[1], reverse=True)

    print("\nTop AI Recommendations:\n")

    for course, score in recommendations[:3]:
        print(f"{course} --> {score*100:.1f}%")

    # Ask Again
    choice = input("\nDo you want another recommendation? (yes/no): ").lower()

    if choice == "no":
        print("\nThank you for using AI Recommendation System!")
        break