# -*- coding: utf-8 -*-
"""AI_Project_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ym7v4TO4KTH1rTYrU4iHWFUbX6m6bfZN
"""

from sklearn.datasets import load_iris

iris = load_iris()

print(iris)

# Dataset Information

print("Feature Names:")
print(iris.feature_names)

print("\nTarget Names:")
print(iris.target_names)

print("\nShape of Dataset:")
print(iris.data.shape)

import pandas as pd

# Convert dataset into DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add target column
df["Target"] = iris.target

# Add flower names
df["Flower Name"] = df["Target"].map({
    0: "Setosa",
    1: "Versicolor",
    2: "Virginica"
})

# Show first 10 rows
df.head(10)

# Count flowers in the dataset

print(df["Flower Name"].value_counts())

# Statistical Summary

df.describe()

from sklearn.model_selection import train_test_split

# Input features
X = iris.data

# Output labels
y = iris.target

# Split data: 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Testing labels shape:", y_test.shape)

from sklearn.preprocessing import StandardScaler

# Create scaler object
scaler = StandardScaler()

# Scale training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Before Scaling:")
print(X_train[0])

print("\nAfter Scaling:")
print(X_train_scaled[0])

from sklearn.neighbors import KNeighborsClassifier

# Create KNN Model
knn = KNeighborsClassifier(n_neighbors=5)

print(knn)

# Train the KNN model

knn.fit(X_train_scaled, y_train)

print("Model Training Completed Successfully!")

# Make predictions on test data

y_pred = knn.predict(X_test_scaled)

print("Predictions:")
print(y_pred)

# Compare Actual vs Predicted

print("Actual Labels:")
print(y_test)

print("\nPredicted Labels:")
print(y_pred)

from sklearn.metrics import accuracy_score

# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:")
print(accuracy)

from sklearn.metrics import confusion_matrix

# Create Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

from sklearn.metrics import f1_score

# Calculate F1 Score
f1 = f1_score(y_test, y_pred, average="weighted")

print("F1 Score:")
print(f1)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names=iris.target_names))



# New flower measurements

new_flower = [[5.1, 3.5, 1.4, 0.2]]

# Scale the new flower
new_flower_scaled = scaler.transform(new_flower)

# Predict
prediction = knn.predict(new_flower_scaled)

print("Predicted Flower:")
print(iris.target_names[prediction[0]])

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(
    iris.data[:,0],
    iris.data[:,2],
    c=iris.target,
    cmap='viridis'
)

plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.title("Iris Dataset Visualization")

plt.colorbar(label="Flower Type")

plt.show()